apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wzntj4b7v-java-springboot
  janus-idp.io/tekton: wzntj4b7v-java-springboot
  backstage.io/kubernetes-id: wzntj4b7v-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wzntj4b7v-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
